name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.16.1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpx elm-test
      - run: pnpm run build
      - name: Prepare release
        run: ./bin/prepare-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
